package th.ac.kmitl.soa.group2.definitions;

public class EtdaXmlTags {

    public static final String ACTUAL_AMOUNT = "ram:ActualAmount";
    public static final String ALLOWANCE_TOTAL_AMOUNT = "ram:AllowanceTotalAmount";
    public static final String BASIS_AMOUNT = "ram:BasisAmount";
    public static final String BUILDING_NAME = "ram:BuildingName";
    public static final String BUILDING_NUMBER = "ram:BuildingNumber";
    public static final String CALCULATED_RATE = "ram:CalculatedRate";
    public static final String CALCULATE_AMOUNT = "ram:CalculatedAmount";
    public static final String CHARGE_INDICATOR = "ram:ChargeIndicator";
    public static final String CHARGE_TOTAL_AMOUNT = "ram:ChargeTotalAmount";
    public static final String CITY_NAME = "ram:CityName";
    public static final String CITY_SUB_DIVISION_NAME = "ram:CitySubDivisionName";
    public static final String COMPLETE_NUMBER = "ram:CompleteNumber";
    public static final String CONTENT = "ram:Content";
    public static final String COUNTRY_ID = "ram:CountryID";
    public static final String COUNTRY_SUB_DIVISION_ID = "ram:CountrySubDivisionID";
    public static final String CREATION_DATE_TIME = "ram:CreationDateTime";
    public static final String CROSS_INDUSTRY_INVOICE = "rsm:CrossIndustryInvoice";
    public static final String DEPARTMENT_NAME = "ram:DepartmentName";
    public static final String DIFFERENCE_INFORMATION_AMOUNT = "ram:DifferenceInformationAmount";
    public static final String EXCHANGED_DOCUMENT = "rsm:ExchangedDocument";
    public static final String EXCHANGED_DOCUMENT_CONTEXT = "rsm:ExchangedDocumentContext";
    public static final String GLOBAL_ID = "ram:GlobalID";
    public static final String GRAND_TOTAL_AMOUNT = "ram:GrandTotalAmount";
    public static final String GUIDELINE_SPECIFIED_DOCUMENT_CONTEXT_PARAMETER = "ram:GuidelineSpecifiedDocumentContextParameter";
    public static final String ID = "ram:ID";
    public static final String INCLUDED_NOTE = "ram:IncludedNote";
    public static final String ISSUE_ASSIGNED_ID = "ram:IssuerAssignedID";
    public static final String ISSUE_DATE_TIME = "ram:IssueDateTime";
    public static final String LINE_FIVE = "ram:LineFive";
    public static final String LINE_FOUR = "ram:LineFour";
    public static final String LINE_ONE = "ram:LineOne";
    public static final String LINE_THREE = "ram:LineThree";
    public static final String LINE_TOTAL_AMOUNT = "ram:LineTotalAmount";
    public static final String LINE_TWO = "ram:LineTwo";
    public static final String NAME = "ram:Name";
    public static final String NET_LINE_TOTAL_AMOUNT = "ram:NetLineTotalAmount";
    public static final String NET_INCLUDING_TAXES_LINE_TOTAL_AMOUNT = "ram:NetIncludingTaxesLineTotalAmount";
    public static final String ORIGINAL_INFORMATION_AMOUNT = "ram:OriginalInformationAmount";
    public static final String PERSON_NAME = "ram:PersonName";
    public static final String POSTAL_TRADE_ADDRESS = "ram:PostalTradeAddress";
    public static final String POSTCODE_CODE = "ram:PostcodeCode";
    public static final String PURPOSE = "ram:Purpose";
    public static final String PURPOSE_CODE = "ram:PurposeCode";
    public static final String REASON = "ram:Reason";
    public static final String REASON_CODE = "ram:ReasonCode";
    public static final String SP_TRADE_ALLOWANCE_CHARGE = "ram:SpecifiedTradeAllowanceCharge";
    public static final String STREET_NAME = "ram:StreetName";
    public static final String SUBJECT = "ram:Subject";
    public static final String TAX_BASIS_TOTAL_AMOUNT = "ram:TaxBasisTotalAmount";
    public static final String TAX_TOTAL_AMOUNT = "ram:TaxTotalAmount";
    public static final String TYPE_CODE = "ram:TypeCode";
    public static final String URI_ID = "ram:URIID";
    public static final String DESCRIPTION = "ram:Description";
    public static final String DUE_DATE_TIME = "ram:DueDateTime";

}
